server:
  port: 8080 # ????
  servlet:
    context-path: /
    encoding:
      charset: UTF-8

spring:
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.125.107.22/instagram?serverTimezone=Asia/Seoul
    username: insta # mysql id
    password: 1234 # mysql pw

  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # jpa
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: false
    properties:
      hibernate.format_sql: true

  # upload
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
